---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: helm-repos
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: main
  secretRef:
    name: helm-repos
  url: ssh://git@git.cygate.io/vipicm/helm-charts.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 10s
  path: ./general/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: helm-repos
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: loki-distributed
  namespace: flux-system
spec:
  interval: 10s
  path: ./zorgo-testing/loki-distributed
  prune: true
  sourceRef:
    kind: GitRepository
    name: helm-repos
# ---
# # apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# # kind: Kustomization
# # metadata:
# #   name: tempo-distributed
# #   namespace: flux-system
# # spec:
# #   interval: 10s
# #   path: ./zorgo-testing/tempo-distributed
# #   prune: true
# #   sourceRef:
# #     kind: GitRepository
# #     name: helm-repos
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: prometheus
#   namespace: flux-system
# spec:
#   interval: 10s
#   path: ./zorgo-testing/helm-prometheus
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: helm-repos