
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 10s
  path: ./helm-charts/zorgo-testing/helm-prometheus
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: loki-distributed
  namespace: flux-system
spec:
  interval: 10s
  path: ./helm-charts/zorgo-testing/loki-distributed
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: tempo-distributed
#   namespace: flux-system
# spec:
#   interval: 10s
#   path: ./helm-charts/zorgo-testing/tempo-distributed
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
